debug: true
help: https://github.com/tpc3/DuckPolice/wiki
discord:
  token: "YOUR_TOKEN_HERE"
  status: "Duck Police is observing you | p.help"
duplicate:
  deletemessage: false
  alert: "reply"
  message: "æ—¢å‡ºè­¦å¯Ÿã ï¼"
  react: "ğŸš¨"
db:
  kind: sqlite3
  parameter: ./db.sqlite
  tableprefix: duckpolice_
guild:
  prefix: p.
  lang: japanese
domain_blacklist:
  - "google.com"
  - "letmegooglethat.com"
  - "discord.com"
user_blacklist:
  - "0000000000000000000" # Add here to ignore user at all
channel_blacklist:
  - "000000000000000000" # Add here to ignore channel at all
log_period: 2592000 # 30 days
