debug: true
help: https://github.com/tpc3/duckpolice/wiki
discord:
  token: "YOUR TOKEN HERE"
  status: "Duck Police is observing you"
duplicate:
  react: "ğŸš¨"
  message: "æ—¢å‡ºè­¦å¯Ÿã ï¼"
db:
  kind: sqlite3
  parameter: ./db.sqlite
  tableprefix: duckpolice_
guild:
  prefix: p.
  lang: japanese
domain_blacklist:
  - "https://google.com"
  - "https://letmegooglethat.com"
user_blacklist:
  - "0000000000000000000" # Add here to ignore user at all
log_period: 2592000 # 30 days