debug: true
help: https://github.com/tpc3/DuckPolice/wiki
discord:
  token: "YOUR_TOKEN_HERE"
  status: "Duck Police is observing you | p.help"
duplicate:
  react: "ğŸš¨"
  message: "æ—¢å‡ºè­¦å¯Ÿã ï¼"
  delete: "âŒ"
  bye: "ã¯ã„..å¸°ã‚Šã¾ã™ã…"
db:
  kind: sqlite3
  parameter: ./db.sqlite
  tableprefix: duckpolice_
guild:
  prefix: p.
  lang: japanese
domain_blacklist:
  - "google.com"
  - "letmegooglethat.com"
user_blacklist:
  - "0000000000000000000" # Add here to ignore user at all
log_period: 2592000 # 30 days
